version : '3.1'

services :
  postgres :
    image : postgres
    volumes :
      - drupal-data:/var/lib/postgresql/data
    restart : always
    environment :
      - POSTGRES_PASSWORD= redhat

  drupal :
    image: drupal
    restart : always
    volumes :
      - drupal-modules:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles 
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes 

    ports :
      - 8080:80

volumes:
  drupal-data:
  drupal-modules:
  drupal-sites:
  drupal-themes:
  drupal-profiles:
